### ISSUE TITLE
Bucklescript watch not working in Docker-compose

### ISSUE THREAD

**Issue by antoniokaplan** [antoniokaplan/reason-react-docker-localdev#1]
Docker file `run` and `exec` commands both work fine and can run both processes in parallel. When run via `docker-compose` webpack will run, but Bucklescript watch command exits.

Here are the two commands that work:
`docker run --rm --name react -d -v $(pwd)/reason-source/src:/usr/app/react-ml/src -v $(pwd)/reason-source/build:/usr/app/react-ml/build  react-reason sh -c 'yarn webpack | yarn start'`

and
`docker run -it -v $(pwd)/reason-source/src:/usr/app/react-ml/src -v $(pwd)/reason-source/build:/usr/app/react-ml/build  react-reason /bin/sh`

**Comment by antoniokaplan** [comment]
This is resolved, and is fixed by adding `stdin_open: true` to the docker-compose file for the bucklescript `bsb -w` service.

**Comment by sorenhoyer** [comment]
Seems like this problem is back
